baseurl: "https://omniopencon.org"
title: "OmniOpenCon"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "G-6YLFK34GVP"

params:
  # Conference info
  Name: "OmniOpenCon"
  Description: "A gathering of people, projects and communities working with open source / data / science / hardware / education"
  Date: "September 26-28, 2024"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Aula Magna & Central Library, POLITEHNICA Bucharest"
  Address: "Splaiul Independenței 313"
  City: "Bucharest"
  #State: "Quintana"
  MapsLocation: "UNSTPB Aula Magna"
  Images: ["/img/badge.png"]
  GoogleMapsKey: "AIzaSyBKGXP4QNvkxcY5_7MxLr7ud09xrSJztJU"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - connect
    - speakers
    - orgs
    - schedule
    - sponsors
    - partners
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    orgs: "Projects and Organizations"
    schedule: "Schedule"
    workshops: "Workshops"
    hackathon: "Hackathon"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"
    connect: "Get Connected!"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://forms.gle/z9EcRCwfV5gZCsMd6"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/rosedu/omniopencon"

  Speakers:
    - name: "Adrian Dușa"
      linkedin: "https://www.linkedin.com/in/adrian-du%C8%99a-5709ba78/"
      github: "https://github.com/dusadrian"
    - name: "Alexandru Olariu"
      linkedin: "https://www.linkedin.com/in/olariu-alexandru/"
      github: "https://github.com/arolariu"
    - name: "Alexandru Radovici"
      linkedin: "https://www.linkedin.com/in/alexandruradovici/"
      github: "https://github.com/alexandruradovici"
    - name: "Alexandru (Sopy) Soponar"
      linkedin: "https://www.linkedin.com/in/sopy/"
      github: "https://github.com/sopyb"
    - name: "Alina Mierluș"
      linkedin: "https://es.linkedin.com/in/alina-mierlus"
      github: "https://github.com/alinamierlus"
    - name: "Andreea Duțulescu"
      linkedin: "https://www.linkedin.com/in/andreea-nicoleta-dutulescu/"
    - name: "Andreia Ocănoaia"
      linkedin: "https://www.linkedin.com/in/andreia-irina-ocanoaia/"
      github: "https://github.com/andreia-oca"
    - name: "Bogdan Popa"
      linkedin: "https://www.linkedin.com/in/popabogdanp/"
      github: "https://github.com/Bogdanp"
    - name: "Dan Tudose"
      linkedin: "https://www.linkedin.com/in/dan-stefan-tudose-0818979b/"
      github: "https://github.com/dantudose"
    - name: "Daniel Băluță"
      linkedin: "https://www.linkedin.com/in/danielbaluta/"
      github: "https://github.com/dbaluta"
    - name: "Daniel Gafni"
      linkedin: "https://www.linkedin.com/in/danielgafni/"
      github: "https://github.com/danielgafni"
    - name: "Darius Mihai"
      github: "https://github.com/darius-m"
    - name: "Doru Ilași"
      linkedin: "https://ro.linkedin.com/in/doruilasi"
      github: "https://github.com/doruilasi"
    - name: "Eduard Stăniloiu"
      linkedin: "https://www.linkedin.com/in/constantin-eduard-staniloiu-35266437/"
      github: "https://github.com/edi33416"
    - name: "Elena Mihăilescu"
      linkedin: "https://www.linkedin.com/in/maria-elena-mihailescu-b9781ba7/"
      github: "https://github.com/elena19m"
    - name: "Georgiana Dolocan"
      linkedin: "https://ro.linkedin.com/in/georgiana-dolocan-1406a1b4"
      github: "https://github.com/GeorgianaElena"
    - name: "Liviu Chirchu"
      linkedin: "https://www.linkedin.com/in/liviu-chircu-05309050/"
      github: "https://github.com/liviuchircu"
    - name: "Mădălin Popa"
      linkedin: "github: https://www.linkedin.com/in/madalinpopa/"
      github: "https://github.com/madalinpopa"
    - name: "Mihai Masala"
      github: "https://github.com/MihaiMasala"
    - name: "Mircea Anton"
      linkedin: "https://www.linkedin.com/in/mirceanton"
      github: "https://github.com/mirceanton"
    - name: "Radu Ciobanu"
      linkedin: "https://www.linkedin.com/in/raduioanciobanu/"
      github: "https://github.com/raduciobanu"
    - name: "Radu Marias"
      linkedin: "https://www.linkedin.com/in/radumarias/"
      github: "https://github.com/radumarias"
    - name: "Radu Marin"
      linkedin: "https://www.linkedin.com/in/radu-corneliu-marin-62897b59/"
      github: "https://github.com/radumarin88"
    - name: "Răzvan Deaconescu"
      linkedin: "https://www.linkedin.com/in/razvandeaconescu/"
      github: "https://github.com/razvand"
    - name: "Răzvan Nițu"
      linkedin: "https://www.linkedin.com/in/razvan-nitu-52175a289/"
      github: "https://github.com/RazvanN7"
    - name: "Robert Bîndar"
      linkedin: "https://www.linkedin.com/in/robertbindar/"
      github: "https://github.com/robertbindar"
    - name: "Rüdiger Klaehn"
      linkedin: "https://www.linkedin.com/in/r%C3%BCdiger-klaehn-5a655673/"
      github: "https://github.com/rklaehn"
    - name: "Sergiu Weisz"
      linkedin: "https://www.linkedin.com/in/sergiu-weisz-794742309/"
      github: "https://github.com/Sergiu121"
    - name: "Ștefan Jumărea"
      linkedin: "https://www.linkedin.com/in/stefan-dorin-jumarea-4081811b9/"
      github: "https://github.com/StefanJum"
    - name: "Ștefan Rușeți"
      linkedin: "https://www.linkedin.com/in/stefan-ruseti-97a011a1/"
      github: "https://github.com/stefanruseti"
    - name: "Teodor Duțu"
      linkedin: "https://www.linkedin.com/in/teodor-dutu-4213a2210/"
      github: "https://github.com/teodutu"
    - name: "Vicențiu Ciorbaru"
      linkedin: "https://www.linkedin.com/in/vicen%C8%9Biu-ciorbaru/"
      github: "https://github.com/cvicentiu"
    - name: "Viorel Anghel"
      linkedin: "https://www.linkedin.com/in/viorelanghel/"
      github: "https://github.com/viorel-anghel"
    - name: "Vlad Năstase"
      github: "https://github.com/VladNastase"

  Orgs:
    - name: "2i2c"
      url: "https://2i2c.org/"
    - name: "ACS (POLITEHNICA Bucharest)"
      url: "https://acs.pub.ro/"
    - name: "Congame"
      url: "https://github.com/marckaufmann/congame"
    - name: "Dagster"
      url: "https://dagster.io/"
    - name: "DLang"
      url: "https://dlang.org/"
    - name: "eSolutions"
      url: "https://www.esolutions.ro/"
    - name: "Iroh"
      url: "https://www.iroh.computer/"
    - name: "JupyterHub"
      url: "https://jupyter.org/hub"
    - name: "LLVM Foundation"
      url: "https://llvm.org/"
    - name: "MariaDB"
      url: "https://mariadb.org/"
    - name: "Microsoft"
      url: "https://www.microsoft.com"
    - name: "NXP"
      url: "https://www.nxp.com/"
    - name: "NuttX"
      url: "https://nuttx.apache.org/"
    - name: "Open Education Hub"
      url: "https://open-education-hub.github.io/"
    - name: "OpenSIPS"
      url: "https://opensips.org/"
    - name: "OxidOS"
      url: "https://oxidos.io/"
    - name: "Rencfs"
      url: "https://github.com/radumarias/rencfs"
    - name: "TileDB"
      url: "https://tiledb.com/"
    - name: "TockOS"
      url: "https://tockos.org/"
    - name: "Unikraft"
      url: "https://unikraft.org/"
    - name: "Unibuc"
      url: "https://unibuc.ro/"
    - name: "Universitad Autonoma de Barcelona"
      url: "https://www.uab.cat/"
    - name: "POLITEHNICA Bucharest"
      url: "https://upb.ro/"

  Connect:
    - name: "Discord"
      logo: "/img/logo-discord.jpg"
      url: "https://bit.ly/OmniOpenCon"
    - name: "Facebook"
      logo: "/img/logo-facebook.png"
      url: "https://www.facebook.com/omniopencon"
    - name: "Instagram"
      logo: "/img/logo-instagram.png"
      url: "https://www.instagram.com/omniopencon"

  Contact:
    - name: "E-mail"
      logo: "/img/logo-email.png"
      url: "mailto:contact@omniopencon.org"
    - name: "Discord"
      logo: "/img/logo-discord.jpg"
      url: "https://bit.ly/OmniOpenCon"

  # List of Sponsors
  Sponsors:
    - name: "Keysight Technologies Romania"
      logo: "/img/logo-keysight.png"
      url: "https://www.linkedin.com/company/ixia-romania/"

  # List of Partners
  Partners:
    - name: "POLITEHNICA Bucharest"
      logo: "/img/logo-unstpb.png"
      url: "https://www.upb.ro"
    - name: "Faculty of Automatic Controls and Computers"
      logo: "/img/logo-acs.png"
      url: "https://acs.pub.ro"
    - name: "ROSEdu (Romanian Open Source Education)"
      logo: "/img/logo-rosedu.png"
      url: "https://www.rosedu.org"

  # The entire schedule
  Schedule:
    - name: "Check-in"
      time: "08:30"
      description: "Welcome, get to know the venue, connect with others."

    - name: "Talks (session 1)"
      time: "09:00"
      description: "First set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Coffee / Tea Break"
      time: "10:30"
      description: "A well deserved break. Grab some coffee or tea, connect with others."

    - name: "Talks (session 2)"
      time: "11:00"
      description: "Second set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Lunch Break"
      time: "12:30"
      description: "Lunch break on your own. Dining options around the POLITEHNICA campus will be provided."

    - name: "Talks (session 3)"
      time: "14:00"
      description: "Third set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Coffee / Tea Break"
      time: "15:30"
      description: "A well deserved break. Grab some coffee or tea, connect with others."

    - name: "Talks (session 4)"
      time: "16:00"
      description: "Fourth set of 3 talks, 30 minutes slot each: presentation + questions"

    - name: "Networking"
      time: "17:30"
      description: "On-site networking with speakers, organizers, participants. A good time to make friends and open up collaboration options."

  Workshops:
    - name: "Check-in"
      time: "08:30"
      description: "Welcome, get to know the venue, connect with others."

    - name: "Workshops (session 1)"
      time: "09:00"
      description: "First workshop slot"

    - name: "Lunch Break"
      time: "12:30"
      description: "Lunch break on your own. Dining options around the POLITEHNICA campus will be provided."

    - name: "Workshops (session 2)"
      time: "14:00"
      description: "Second workshop slot"

    - name: "Networking"
      time: "17:30"
      description: "On-site networking with speakers, organizers, participants. A good time to make friends and open up collaboration options."
